#!/usr/bin/perl

system("open -a XCode src/*.cpp src/*.c");
system("open -a XCode include/*.h");
$otdlFiles = `find Materials/Trees -name default.otdl`;
$otdlFiles =~ s/\n/ /g;
system("open -a XCode ~/.bashrc Makefile README.md openSrc *.pl compilePmod 812/812.oldf src/*.glsl CMakeLists.txt web/*.js web/views/*.ejs web/views/*.js docs/*.md tests/*.oldf tests/*.pl *.json Materials/Trees/Regions/*.json $otdlFiles");
